Added fee struct
provenance-io/provwasm pull request #107
Opened 2023-03-14 04:51 UTC by Taztingo

Added the fee structure that will be commonly used by contracts that introduce message fees.

2023-03-16 14:04 UTC, iramiller approved these changes

2023-03-16 14:48 UTC, nullpointer0x00 requested changes
Change log?

2023-03-17 04:37 UTC, iramiller submitted a review, later dismissed

2023-04-06 18:03 UTC, nullpointer0x00 approved these changes

2023-04-06 18:51 UTC, kwtalley approved these changes

2023-04-06 18:51 UTC, kwtalley commented on packages/bindings/src/querier.rs
> +            return Err(StdError::not_found(format!("record not found: {name}")));
probably a typo since this would get rid of the `name` value for the string

2023-04-06 18:56 UTC, merged