Taztingo/108 implement from
provenance-io/provwasm pull request #109
Opened 2023-03-16 03:33 UTC by Taztingo

Added missing implementation of From. This will allow us to use ProvenanceMsg in place of CosmosMsg<ProvenanceMsg>.

2023-03-16 14:03 UTC, iramiller submitted a review, later dismissed

2023-03-16 14:47 UTC, nullpointer0x00 requested changes
Change log?

2023-03-17 04:38 UTC, iramiller submitted a review, later dismissed

2023-03-20 14:23 UTC, kwtalley approved these changes

2023-04-05 20:42 UTC, nullpointer0x00 approved these changes

2023-04-05 21:19 UTC, merged